name: CI - OrnoPlante

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run Prisma Validate
        run: npx prisma validate
        working-directory: backend

      - name: Run Backend Tests
        run: npm test
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build Next.js
        run: npm run build
        working-directory: frontend
